default: &default
  adapter: postgresql
  username: Horacioroz
  password:
  host: 127.0.0.1
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nomster_development

test:
  <<: *default
  database: nomster_test

production:
  <<: *default
  database: nomster_production
